spring:
  messages.basename: messages,errors
  datasource:
    url: jdbc:mysql://capstonedb.clw4wuwea38h.ap-northeast-2.rds.amazonaws.com:3306/Capstone
    username: yoona
    password: 32211768
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        default_batch_fetch_size: 200
    open-in-view: false
    defer-datasource-initialization: true
  servlet.multipart:
    max-file-size: 15MB
    max-request-size: 15MB
  data:
    redis:
      password : 32211768
      host: 127.0.0.1
      port : 6379
  aop:
    auto: false



server:
  tomcat:
    threads:
      max: 24

logging:
  level:
    root: info
    org.hibernate:
      sql: debug
    org.springframework: DEBUG
app:
  enable-test-controller: true
  cors: "*"
  auth:
    find-expiration: PT1H
    sms:
      digit-count: 6
    jwt:
      access-expiration: P3D
      refresh-expiration: P15D
      secret-key: d67d6897c5e4b70e64cebe866382eed737ffc2400ebcfb7c3f517443a2ea0deb937c5fdd37046f960872cb59dbeaf546980abc180731f22717f9275854b52857

  user:
    default-user-id: 1
    delete-period: P6M



cloud:
  aws:
    s3:
      bucket: capstoneawsbuckett
    credentials:
      secret-key: sQxoMJcYpqKmW5qOWtCHl2kYFwcufiUdVjTwB4hI
      access-key: AKIAXYKJSUT76CB7WD45
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false



springdoc:
  packages-to-scan: "com.Capstone.Project"
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    enabled: true
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    enabled: true
    groups:
      enabled: true








